package dominio.enums;

public enum RolSistema {
    CLIENTE_PERSONA_NATURAL,
    CLIENTE_EMPRESA,
    EMPLEADO_VENTANILLA,
    EMPLEADO_COMERCIAL,
    EMPLEADO_EMPRESA,
    SUPERVISOR_EMPRESA,
    ANALISTA_INTERNO
}